services:
  debian-vps:
    build: .
    container_name: vps

    restart: unless-stopped

    tty: true
    stdin_open: true

    cpus: 6
    mem_limit: 20g
    memswap_limit: 20g

    shm_size: "4gb"

    volumes:
      - /home/user/myapp/code:/root/code
      - /mnt:/mnt-host

    ports:
      - "8080:8080"
